### ISSUE TITLE
post instagram doesn't work

### ISSUE THREAD

**Issue by fmchan** [b31ngD3v/instagram-post-scheduler#1]
selenium.common.exceptions.NoSuchElementException: Message: no such element: Unable to locate element: {"method":"css selector","selector":".cmbtv"}

**Comment by b31ngd3v** [comment]
mute line 32

**Comment by b31ngd3v** [comment]
Since you not replied, I'm closing the issue.

**Comment by fmchan** [comment]
since I cannot simulate the error again on mac
